language: csharp
solution: Constant.sln
install:
  - nuget restore ./Constant.sln
  - nuget install xunit.runners -Version 2.4.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./Constant.sln
  - mono ./testrunner/xunit.runners.2.4.1/tools/xunit.console.clr4.exe ./Constant.Tests.Unit/bin/Release/Constant.Tests.Unit.dll
