language: csharp
solution: Constant.sln
mono: none
dotnet: 2.2
dist: xenial
sudo: required

install:
  - dotnet restore ./Constant.sln
script:
  - dotnet build -c Release ./Constant.sln
  - dotnet test ./Constant.Tests.Unit/Constant.Tests.Unit.csproj
