language: csharp
solution: Constant.sln
install:
  - nuget restore Constant/Constant.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Constant/Constant.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Constant.Tests.Unit/bin/Release/Constant.Tests.Unit.dll
